### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by flexbox** [flexbox/artaufeminin#65]
make sure we are [only using prose](https://github.com/tailwindlabs/tailwindcss-typography) on the pages

- [x] episodes https://artaufeminin.fr/episodes/1467bafb-eeab-4943-9bcf-d9c3e1bccc5f
- [x] articles https://artaufeminin.fr/article/tamara-barrage-questions
- [x] about https://artaufeminin.fr/about

**Comment by MatthysDucrocq** [comment]
Fix
