### ISSUE TITLE
Hr to remake

### ISSUE THREAD

**Issue by MatthysDucrocq** [flexbox/artaufeminin#71]
change

<img width="816" alt="Capture d’écran 2021-11-26 à 16 59 24" src="https://user-images.githubusercontent.com/81434852/143606524-d788a4b1-94e7-4842-a9ae-870ab1fda117.png">

to 
<img width="857" alt="Capture d’écran 2021-11-26 à 16 58 41" src="https://user-images.githubusercontent.com/81434852/143606457-40c93a39-e010-45f9-bd45-d590695f8c24.png">

**Comment by flexbox** [comment]
Can you 

- [ ] add variables in a `platette.css` file?
- [ ] Create a `typography.story.tsx` file to have example of isolated components

**Comment by MatthysDucrocq** [comment]
Fix
