### ISSUE TITLE
/links page

### ISSUE THREAD

**Issue by flexbox** [flexbox/artaufeminin#72]
As a mobile user
I can see all entries
So that explore links

- [ ] fix button size

**Actual**
<img width="401" alt="image" src="https://user-images.githubusercontent.com/360936/144455829-063f0e34-69ee-4543-85d8-d0d6ae657b27.png">

**Expected**
<img width="440" alt="image" src="https://user-images.githubusercontent.com/360936/144455780-2b467d05-3ba0-42f8-a49b-5ef1d657841a.png">

**Comment by MatthysDucrocq** [comment]
fix link page closes #72
