### ISSUE TITLE
Press Kit: new page

### ISSUE THREAD

**Issue by flexbox** [flexbox/artaufeminin#76]
As a journalist
I can have infomations about the website / brand
So that I can include references

---

- [x] Create a new page

Take this as an example
https://www.notion.so/Raycast-Press-Kit-ce1ccf8306b14ac8b8d47b3276bf34e0
https://www.binge.audio/presse

- [x] include LOGOS from 
  - https://pantherepremiere.org/texte/la-peinture-apres-la-fin-de-la-peinture/
  - https://podtail.com/fi/podcast/art-au-feminin/
  - https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy85NDgzZGY4L3BvZGNhc3QvcnNz
  - https://www.francetvinfo.fr/monde/afrique/culture-africaine/le-musee-d-art-moderne-de-paris-celebre-avec-the-power-of-my-hands-les-femmes-artistes-dafrique-et-de-la-diaspora_4718991.html
  - https://www.amylee.fr/podcast-art-feminin/
  - https://cultea.fr/memoria-recits-dune-autre-histoire-lexposition-actuelle-du-frac-nouvelle-aquitaine-meca-a-bordeaux.html
  
  Inspiration:

  
  
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/360936/145073893-f8dced82-33ec-4983-be61-59a6647a8551.png">

- [ ] External link

**Comment by MatthysDucrocq** [comment]
Added

**Comment by flexbox** [comment]
Can you add a brand section like this?


![image](https://user-images.githubusercontent.com/360936/147263540-6ead5e3f-dc7a-4572-a6dc-3914ca7b5afe.png)

with logos as downloadable pictures like https://davidl.fr/raid/presse
