### ISSUE TITLE
Better Header Navigation

### ISSUE THREAD

**Issue by flexbox** [flexbox/artaufeminin#92]
As a visitor
I can identify clearly the navigation
So that I am not lost 

_Example_:
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/360936/147163870-bda41d2d-6439-40fb-81ef-30e95de50466.png">

https://www.beauxarts.com/conferences/

- [x] refactor `Header.tsx` component
- [x] create a `header.stories.tsx` file
- [x] make it work on mobile
- [x] Add an active state

**Comment by MatthysDucrocq** [comment]
Fix
